name: Bug Report
description: Report a bug or issue with the app
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please fill out the information below to help us fix the problem.
  
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the app are you using? You can find this in the app settings.
      placeholder: "e.g., 1.0.0"
    validations:
      required: true
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug or issue you encountered.
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Please describe what you expected to happen instead.
      placeholder: Tell us what you expected!
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: false
  
  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information about the problem here, such as screenshots or error messages.
      placeholder: Any additional details that might help us understand the issue
    validations:
      required: false
