name: Feedback
description: Share your feedback about the app
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your feedback! We appreciate your input to help make the app better.
  
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the app are you using? You can find this in the app settings.
      placeholder: "e.g., 1.0.0"
    validations:
      required: true
  
  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback are you providing?
      options:
        - General feedback
        - User experience
        - Performance
        - Design/Appearance
        - Other
    validations:
      required: true
  
  - type: textarea
    id: feedback
    attributes:
      label: Your Feedback
      description: Please share your thoughts, suggestions, or comments about the app.
      placeholder: Tell us what you think!
    validations:
      required: true
  
  - type: dropdown
    id: rating
    attributes:
      label: Overall Experience
      description: How would you rate your overall experience with the app?
      options:
        - Excellent
        - Good
        - Average
        - Poor
        - Very Poor
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Comments
      description: Any other comments or suggestions?
      placeholder: Any additional information you'd like to share
    validations:
      required: false
